server:
  port: 8090
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mapper路径和实体对象路径
mybatis:
  #  Mapper文件存放的位置
  mapperLocations: classpath:mapper/**/*.xml
  #  实体类所在的包
  typeAliasesPackage: com.valvulas.fancky.model.entity

#默认log
#logging:
#  #  path没起作用
# # path:
#  file: logs/log.log

logging:
  config: classpath:log4j2.yml
#开发配置
spring:
  application:
    name: SpringBootProject
  thymeleaf:
  #      view:
  #        prefix: /
  #        suffix: .html
  #   #  html
  #     prefix: classpath:/templates/
  #      #图片
  #    resources:
  #      static-locations: classpath:/
  #解决：Unable to register MBean [HikariDataSource (null)] with key 'dataSource';
  jmx:
   enabled: false
  datasource:
    #    #注意冒号有空格
    #    url: jdbc:mysql://39.97.186.80:3306/valvulas?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #  #  url: jdbc:mysql://127.0.0.1:3306/valvulas?useUnicode=true&characterEncoding=utf8&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    username: root
    #    password: Li5rui31987.
    #  #  password: 123456


    #D:\fancky\Git\Java\valvulas\sqlite
#    unix
#    url: jdbc:sqlite:/usr/sqlite/valvulas.db
    # #方式一：磁盘路径  D:\Work\Project\Git\java\valvulas\sqlite
    url: jdbc:sqlite:D:/Work/Project/Git/Java/valvulas/sqlite/valvulas.db
    #方式二：引用项目中的文件:resources/static/sqlite//valvulas.db
    # 引用项目内的db文件，必须以jdbc:sqlite::resource: 开头
#    url: jdbc:sqlite::resource:static/sqlite/valvulas.db
    driver-class-name: org.sqlite.JDBC
